# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jenkins\u4efb\u52a1\u540d\u79f0')),
                ('last_success_num', models.IntegerField(default=0, verbose_name='\u6700\u540e\u4e00\u6b21\u6210\u529f\u6784\u5efa\u7248\u672c\u53f7')),
            ],
            options={
                'verbose_name': 'Jenkins\u4efb\u52a1\u5217\u8868',
                'verbose_name_plural': 'Jenkins\u4efb\u52a1\u5217\u8868',
            },
        ),
    ]
