# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChangeHistory',
            fields=[
                ('id', models.IntegerField()),
                ('filename', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('modified_user', models.CharField(max_length=20)),
                ('modified_time', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1)),
                ('application_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u4fee\u6539\u5386\u53f2\u8bb0\u5f55\u8868',
                'db_table': 'config_historicalconfigfile',
                'managed': False,
                'verbose_name_plural': '\u914d\u7f6e\u4fee\u6539\u5386\u53f2\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name': '\u6a21\u62df\u7528\u6237\u8868\u7ed9ConfigChangeHistory\u8868\u7528',
                'verbose_name_plural': '\u6a21\u62df\u7528\u6237\u8868\u7ed9ConfigChangeHistory\u8868\u7528',
            },
        ),
        migrations.CreateModel(
            name='Configfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30, verbose_name='\u914d\u7f6e\u6587\u4ef6\u540d\u79f0')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u5185\u5bb9')),
                ('modified_user', models.CharField(max_length=20, verbose_name='\u4fee\u6539\u4eba')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Application', verbose_name='\u6240\u5c5e\u5e94\u7528')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u6587\u4ef6\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u914d\u7f6e\u6587\u4ef6\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfigfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('filename', models.CharField(max_length=30, verbose_name='\u914d\u7f6e\u6587\u4ef6\u540d\u79f0')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u5185\u5bb9')),
                ('modified_user', models.CharField(max_length=20, verbose_name='\u4fee\u6539\u4eba')),
                ('modified_time', models.DateTimeField(blank=True, editable=False, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.Application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': '\u4fee\u6539\u5386\u53f2\u8bb0\u5f55',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
