# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ECS_deploy_status', models.CharField(default='N', max_length=1, verbose_name='ECS\u53d1\u5e03\u72b6\u6001')),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ECS', verbose_name='\u53d1\u5e03\u5e94\u7528\u6240\u5c5eECS')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Application')),
                ('deploy_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.DeployApply', verbose_name='\u6240\u5c5e\u53d1\u5e03\u7533\u8bf7\u5355')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u5e94\u7528\u4e0eECS\u5173\u8054\u5173\u7cfb\u8868',
                'verbose_name_plural': '\u53d1\u5e03\u5e94\u7528\u4e0eECS\u5173\u8054\u5173\u7cfb\u8868',
            },
        ),
        migrations.CreateModel(
            name='DeployItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_order_by', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u53d1\u5e03\u987a\u5e8f')),
                ('jenkins_version', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jenkins\u7248\u672c\u53f7')),
                ('type', models.CharField(choices=[('T', '\u4e3b\u5e72'), ('B', '\u5206\u652f')], default='T', max_length=1, verbose_name='\u4ee3\u7801\u7c7b\u578b')),
                ('deploy_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Application', verbose_name='\u53d1\u5e03\u5e94\u7528')),
                ('deploy_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.DeployApply', verbose_name='\u6240\u5c5e\u53d1\u5e03\u7533\u8bf7\u5355')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u9879\u76ee\u5217\u8868',
                'verbose_name_plural': '\u53d1\u5e03\u9879\u76ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', '\u5df2\u53d1\u5e03'), ('N', '\u5f85\u53d1\u5e03')], default='N', max_length=1, verbose_name='\u914d\u7f6e\u53d1\u5e03\u72b6\u6001')),
                ('modified_user', models.CharField(max_length=20, verbose_name='\u4fee\u6539\u4eba')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ECS', verbose_name='\u6240\u5c5e\u53d1\u5e03ECS')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Application', verbose_name='\u6240\u5c5e\u53d1\u5e03\u5e94\u7528')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u53d1\u5e03\u72b6\u6001',
                'verbose_name_plural': '\u914d\u7f6e\u53d1\u5e03\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='SLBHealthStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBStatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='SLB\u542f\u7528\u72b6\u6001')),
                ('health_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='SLB\u540e\u7aef\u5e94\u7528\u5065\u5eb7\u72b6\u6001')),
                ('ECS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ECS', verbose_name='\u6240\u5c5eECS')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.SLB', verbose_name='\u6240\u5c5eSLB')),
            ],
        ),
        migrations.CreateModel(
            name='SLBToApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.SLB', verbose_name='\u6240\u5c5eSLB')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Application', verbose_name='\u6240\u5c5e\u5e94\u7528')),
            ],
            options={
                'verbose_name': 'SLB\u4e0e\u5e94\u7528\u5173\u7cfb\u8868',
                'verbose_name_plural': 'SLB\u4e0e\u5e94\u7528\u5173\u7cfb\u8868',
            },
        ),
    ]
