# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20181010_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slbhealthstatus',
            old_name='SLBstatus',
            new_name='SLBStatus',
        ),
        migrations.RenameField(
            model_name='slbhealthstatus',
            old_name='healthstatus',
            new_name='health_status',
        ),
    ]
