# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20181020_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slbhealthstatus',
            name='health_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SLB\u540e\u7aef\u5e94\u7528\u5065\u5eb7\u72b6\u6001'),
        ),
    ]
