# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='\u5e94\u7528\u5168\u79f0')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5e94\u7528\u7b80\u79f0')),
                ('config_dir_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u914d\u7f6e\u6587\u4ef6\u5939\u540d\u79f0')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='\u5e94\u7528\u7aef\u53e3')),
                ('test_page', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6d4b\u8bd5\u9875\u9762')),
                ('dev_charge', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7814\u53d1\u8d1f\u8d23\u4eba')),
                ('deploy_attention', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u6ce8\u610f\u4e8b\u9879')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('modified_user', models.CharField(default='admin', max_length=20, verbose_name='\u4fee\u6539\u4eba')),
                ('status', models.CharField(blank=True, choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1, null=True, verbose_name='\u72b6\u6001')),
                ('random_id', models.IntegerField(blank=True, null=True, verbose_name='\u5e94\u7528\u968f\u673aID')),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.BigIntegerField(verbose_name='\u968f\u673a\u5e94\u7528\u65cfid')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528\u65cf\u522b\u540d')),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u65cf\u7fa4\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u5e94\u7528\u65cf\u7fa4\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='ECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ECS\u540d\u79f0')),
                ('instance_id', models.CharField(max_length=30, verbose_name='\u5b9e\u4f8bID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP\u5730\u5740')),
                ('status', models.CharField(choices=[('Y', 'enable'), ('N', 'disable')], default='Y', max_length=1)),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('recently_cpu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1CPU\u4f7f\u7528\u7387')),
                ('recently_memory', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1\u5185\u5b58\u4f7f\u7528\u7387')),
                ('recently_disk_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u6700\u8fd1\u78c1\u76d8\u4f7f\u7528\u7387')),
                ('regionId', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6240\u5728\u533a\u57df')),
                ('expired_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('memory', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('os_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('instance_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5b9e\u4f8b\u72b6\u6001')),
                ('network_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('cpu', models.CharField(blank=True, max_length=5, null=True, verbose_name='CPU\u6838\u6570')),
                ('public_ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='\u516c\u7f51IP')),
                ('osname', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'ECS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'ECS\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='RDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100, verbose_name='\u5b9e\u4f8bID')),
                ('instance_alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b9e\u4f8b\u522b\u540d')),
                ('network_type', models.CharField(max_length=20, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('engine', models.CharField(max_length=30, verbose_name='\u5f15\u64ce\u7c7b\u578b')),
                ('engine_version', models.CharField(max_length=50, verbose_name='\u5f15\u64ce\u7248\u672c')),
                ('status', models.CharField(max_length=30, verbose_name='\u72b6\u6001')),
                ('expire_time', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'RDS\u4fe1\u606f\u8868',
                'verbose_name_plural': 'RDS\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='RDSUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU\u4f7f\u7528\u7387')),
                ('io_usage', models.FloatField(blank=True, null=True, verbose_name='IOPS\u4f7f\u7528\u7387')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='\u78c1\u76d8\u4f7f\u7528\u7387')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('rds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.RDS', verbose_name='\u6240\u5c5eRDS')),
            ],
            options={
                'verbose_name': 'RDS\u8d44\u6e90\u4f7f\u7528\u7387\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'RDS\u8d44\u6e90\u4f7f\u7528\u7387\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='SLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8bID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('status', models.CharField(max_length=30, verbose_name='\u5b9e\u4f8b\u72b6\u6001')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP\u5730\u5740')),
                ('network_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('address_type', models.CharField(max_length=10, verbose_name='IP\u7c7b\u578b\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d1f\u8f7d\u5747\u8861\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u8d1f\u8f7d\u5747\u8861\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='ECS_lists',
            field=models.ManyToManyField(to='system.ECS', verbose_name='\u5173\u8054ECS\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ApplicationRace', verbose_name='\u5173\u8054\u7ad9\u70b9\u65cf'),
        ),
    ]
