# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20181010_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(default=0, verbose_name='\u5e94\u7528\u968f\u673aID'),
            preserve_default=False,
        ),
    ]
