# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20181017_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='random_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e94\u7528\u968f\u673aID'),
        ),
    ]
