# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20181018_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrace',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528\u65cf\u522b\u540d'),
        ),
        migrations.AlterField(
            model_name='applicationrace',
            name='race_id',
            field=models.BigIntegerField(verbose_name='\u968f\u673a\u5e94\u7528\u65cfid'),
        ),
    ]
