# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20181018_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e94\u7528\u7aef\u53e3'),
        ),
    ]
