# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20181019_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ApplicationRace', verbose_name='\u5173\u8054\u7ad9\u70b9\u65cf'),
        ),
    ]
