# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_slbapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slbapplication',
            name='SLB',
        ),
        migrations.RemoveField(
            model_name='slbapplication',
            name='application',
        ),
        migrations.DeleteModel(
            name='SLBApplication',
        ),
    ]
