# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_project', models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u7f16\u53f7')),
                ('status', models.CharField(choices=[('WC', '\u5f85\u63d0\u4ea4'), ('WD', '\u5f85\u53d1\u5e03'), ('C', '\u5df2\u53d6\u6d88'), ('D', '\u5df2\u53d1\u5e03'), ('DA', '\u7814\u53d1\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('OA', '\u8fd0\u7ef4\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('EA', '\u8fd0\u7ef4\u5de5\u7a0b\u5e08\u5ba1\u6279\u4e2d'), ('TA', '\u6d4b\u8bd5\u7ecf\u7406\u5ba1\u6279\u4e2d'), ('TDA', '\u6280\u672f\u603b\u76d1\u5ba1\u6279\u4e2d')], default='WC', max_length=3, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('apply_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('deploy_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u53d1\u5e03\u4eba')),
                ('deploy_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b9e\u9645\u53d1\u5e03\u65f6\u95f4')),
                ('conf_amend_explain', models.TextField(blank=True, null=True, verbose_name='\u914d\u7f6e\u4fee\u6539\u8bf4\u660e')),
                ('remark_explain', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u4e8b\u9879')),
                ('verify_result', models.CharField(blank=True, choices=[('Y', '\u5ba1\u6838\u901a\u8fc7'), ('N', '\u5ba1\u6838\u4e0d\u901a\u8fc7')], max_length=1, null=True, verbose_name='\u5ba1\u6838\u7ed3\u679c')),
                ('wish_deploy_time', models.DateField(blank=True, null=True, verbose_name='\u671f\u671b\u53d1\u5e03\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7533\u8bf7\u5217\u8868',
                'verbose_name_plural': '\u53d1\u5e03\u7533\u8bf7\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='DeployApplyOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='\u53d1\u5e03\u5e94\u7528\u4ee3\u7801\u7c7b\u578b')),
                ('operator_name', models.CharField(max_length=30, verbose_name='\u64cd\u4f5c\u4eba')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('deploy_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.DeployApply', verbose_name='\u6240\u5c5e\u7533\u8bf7\u53d1\u5e03\u5355')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7533\u8bf7\u5ba1\u6279\u65e5\u5fd7',
                'verbose_name_plural': '\u53d1\u5e03\u7533\u8bf7\u5ba1\u6279\u65e5\u5fd7',
            },
        ),
    ]
